== Ditaa

Requires gem `asciidoctor-diagram-ditaamini` or Ditaa on the executables path.

[ditaa, zasoby/genDiag/diag_Ditaa, png]
.cBLK should colour it in black but doesn't work?
....
                   +-------------+
                   | Asciidoctor |-------+
                   |  Diagram    |       |
                   +-------------+       | PNG out
                       ^                 |
                       | ditaa in        |
                       |                 v
 +--------+   +--------+----+    /----------------\
 |        | --+ Asciidoctor +--> |                |
 |  Text  |   +-------------+    |Beautiful output|
 |Document|   |   !magic!   |    |                |
 |     {d}|   |             |    |  CBLK          |
 +---+----+   +-------------+    \----------------/
     :                                   ^
     |          Lots of work             |
     +-----------------------------------+
....

=== Colours

`cXXX` colours, either give a hex or `BLK`, `BLU` etc.

- On previous diagram we used `CBLK`, but it should have been `cBLK` to colour in black.
- Similarly, `cYEL` gives yellow, while `cYel` shows up as a text.
- Also, note that yellow `Asciidoctor Diagram` has rounded corners, colour yellow, and word `Diagram` to the right. That's because:

----
/-------------\
| Asciidoctor |
| cYEL Diagram|
\-------------/
----

Full diagram:

[ditaa, zasoby/genDiag/diag_Ditaa_frills, png]
.Shows colours and rendering options and other frills
....
                   /-------------\
                   | Asciidoctor |-------+
                   | cYEL Diagram|       |
                   \-------------/       | PNG out
                       ^                 |
                       | ditaa in        |
                       |                 v
 +--------+   +--------+----+    /----------------\
 |        | --+ Asciidoctor +--> |                |
 |  Text  |   +-------------+    |Beautiful output|
 |Document|   |   !magic!   |    |                |
 |cYel {d}|   |  cBLU       |    |  cBLK          |
 +---+----+   +-------------+    \----------------/
     :                                   ^
     |          Lots of work             |
     +-----------------------------------+
....
